version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    container_name: foodtoeat-db-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fte-db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      # host:image
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    image: foodtoeat-backend:4.0
    container_name: foodtoeat-backend
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/fte-db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      # host:image
      - "8081:8081"
    networks:
      - app-network

  frontend:
    image: foodtoeat-frontend:1.0
    container_name: foodtoeat-frontend
    ports:
      - "8082:80"  # Frontend dostępny pod portem 8082
    networks:
      - app-network


networks:
  app-network:

volumes:
  mysql_data:
