services:
  mysql:
    image: mysql:latest
    container_name: fte-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: polki
      MYSQL_DATABASE: fresh_food
    ports:
      - "3307:3306"
    volumes:
      - fte-db-vol-PROD:/var/lib/mysql

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

    networks:
      - app-network

  backend:
    image: fte-be
    container_name: fte_backend-container
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/fresh_food?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: polki
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    image: fte25-fe
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  fte-db-vol-PROD:
    external: true # Volume exists and has been created outside of docker-compose.

networks:
  app-network:
    driver: bridge